# Generated by Django 3.2 on 2023-03-09 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценки только от 1 до 10!'), django.core.validators.MaxValueValidator(10, 'Оценки только от 1 до 10!')]),
        ),
    ]
